[package]
authors = ["Lee Lup Yuen <luppy@appkaki.com>"]
edition = "2018"
readme = "README.md"
name = "myapp"
version = "0.1.0"

[dependencies]
##rust-libcore = "0.0.3" # Must use libcore when linking with gcc
cty = "0.2.0"
cstr_core = "0.1.2"

# [dependencies.rust-libcore]
# version = "0.0.3" # Must use libcore when linking with gcc
# default-features = false # do not include the default features
# features = []

[lib]
name = "mylib"
test = false
bench = false

# For `cargo build`
[profile.dev]
panic = "abort" # disable stack unwinding on panic

# For `cargo build --release`
[profile.release]
panic = "abort" # disable stack unwinding on panic
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations

# For `cargo fix`
#[[bin]]
#name = "myapp"
#test = false
#bench = false
